Change some comment formatting

diff --git a/part2/new_user b/part2/new_user
--- a/part2/new_user
+++ b/part2/new_user
@@ -7,9 +7,17 @@
 # Group configuration
 # Setup password
 # Reference:
-#
+# [10] https://unix.stackexchange.com/questions/153225/what-steps-to-add-a-user-to-a-system-without-using-useradd-adduser
+# [11] https://opensource.com/article/19/12/help-bash-program
 
+if [[ $EUID -ne 0 ]];then                # Check if the script is run by root privillege [8]
+  echo "You need to 'sudo' this script"  # Print an error message
+  exit 1                                 # Exit the script
+fi
 
+################################################################################
+# Help                                                                         #
+################################################################################
 show_help() {
     echo "Usage: $0 -u <username> -s <shell> -g <group1,group2,...> -i <User ID Info>"
     echo "  -u <username>           Username of the new user (required)"
@@ -18,6 +26,7 @@ show_help() {
     echo "  -i <User ID Info>       Extra information about the user"
     exit 0
 }
+# Function display what options it 
 
 shell="bin/bash"
 group=()
@@ -44,21 +53,22 @@ if [[ -n $(awk -F: -v username="$username" '$1 == username {print "String found 
     echo "Username found in file"
     exit 1
 else
-    echo "Username not found in file"
+    echo "Valid Username"
 fi
 
 uid=$(awk -F: '$3 >= 1000 && $3 <= 65533 { if ($3 > max) max = $3 } END { if (max >= 1000) print max+1; else print 1000 }' /etc/passwd)
 gid=$(awk -F: '$3 >= 1000 && $4 <= 65533 { if ($4 > max) max = $4 } END { if (max >= 1000) print max+1; else print 1000 }' /etc/passwd)
-
+user_home="/home/$username"
 user_entry="$username:x:$uid:$gid:$info:$user_home:$shell"
-echo "$user_entry" >> /etc/passwd
+echo "$user_entry" >> /etc/passwd 
 echo "$username:!*::::::" >> /etc/shadow
 echo "$username:x:$gid:" >> /etc/group
 
-user_home="/home/$username"
+
 mkdir -p "$user_home"
 cp -r /etc/skel/. "$user_home"
 chown -R "$username:$gid" "$user_home"
+chmod -R 751 "$user_home"
 
 groups=($(awk -F, '{for(i=1; i<=NF; i++) print $i}' <<< "$groups"))
 for ((i=0; i<${#groups[@]}; i++)); do
@@ -76,3 +86,5 @@ for ((i=0; i<${#groups[@]}; i++)); do
     }' /etc/group > /etc/group.tmp && mv /etc/group.tmp /etc/group
     echo "User $username added to group ${groups[i]}"
 done
+
+passwd $username
