Uniform style and Add more description

diff --git a/part1/setup b/part1/setup
--- a/part1/setup
+++ b/part1/setup
@@ -1,6 +1,12 @@
 #!/bin/bash
 # Filename: setup
 # Description: Run setup and link scripts
+# Reference: https://ss64.com/bash/ps.html [8]
 
-./install   # Run setup script
-./link    # Run link script
+
+if [[ $UID -ne 0 ]];then                # Check if the script is run by root privillege [8]
+  echo "You need to 'sudo' this script" # Print an error message
+  exit 1                                # Exit the script
+fi
+./install                               # Run setup script
+./link                                  # Run link script
